cc_binary (
  name = 'test_indexer',
  srcs = ['test_indexer.cc'],
  deps = [
    '//common:base',
    '//server/searcher:server',
  ]
)

# cc_test (
#   name = 'test_indexer',
#   srcs = ['test_indexer.cc'],
#   deps = [
#     '//common:base',
#     '//server/searcher:server',
#   ]
# )
