cc_library (
  name = 'search_master',
  srcs = [
    'search_master.cc',
  ],
  deps = [
    '//common:base',
    '//server/http:http_server',
    '//server/http:http_client',
    '//thirdparty:cjson'
  ]
)
