cc_binary (
  name = 'search_backend',
  srcs = ['search_backend.cc'],
  deps = [
    '//common:base',
    '//server/backend:server'
  ]
)

cc_binary (
  name = 'search_root',
  srcs = ['search_root.cc'],
  deps = [
    '//common:base',
    '//server/master:search_master'
  ]
)
