/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef doc_id_CONSTANTS_H
#define doc_id_CONSTANTS_H

#include "doc_id_types.h"



class doc_idConstants {
 public:
  doc_idConstants();

};

extern const doc_idConstants g_doc_id_constants;



#endif
