/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef doc_info_CONSTANTS_H
#define doc_info_CONSTANTS_H

#include "doc_info_types.h"



class doc_infoConstants {
 public:
  doc_infoConstants();

};

extern const doc_infoConstants g_doc_info_constants;



#endif
