/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "doc_info_constants.h"



const doc_infoConstants g_doc_info_constants;

doc_infoConstants::doc_infoConstants() {
}



