/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "doc_id_constants.h"



const doc_idConstants g_doc_id_constants;

doc_idConstants::doc_idConstants() {
}



