/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef indexed_field_names_CONSTANTS_H
#define indexed_field_names_CONSTANTS_H

#include "indexed_field_names_types.h"



class indexed_field_namesConstants {
 public:
  indexed_field_namesConstants();

};

extern const indexed_field_namesConstants g_indexed_field_names_constants;



#endif
