/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "indexed_field_names_constants.h"



const indexed_field_namesConstants g_indexed_field_names_constants;

indexed_field_namesConstants::indexed_field_namesConstants() {
}



