/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "raw_doc_constants.h"



const raw_docConstants g_raw_doc_constants;

raw_docConstants::raw_docConstants() {
}



