/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef raw_doc_CONSTANTS_H
#define raw_doc_CONSTANTS_H

#include "raw_doc_types.h"



class raw_docConstants {
 public:
  raw_docConstants();

};

extern const raw_docConstants g_raw_doc_constants;



#endif
