/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef request_CONSTANTS_H
#define request_CONSTANTS_H

#include "request_types.h"



class requestConstants {
 public:
  requestConstants();

};

extern const requestConstants g_request_constants;



#endif
