/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef response_CONSTANTS_H
#define response_CONSTANTS_H

#include "response_types.h"



class responseConstants {
 public:
  responseConstants();

};

extern const responseConstants g_response_constants;



#endif
