/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "url_params_constants.h"



const url_paramsConstants g_url_params_constants;

url_paramsConstants::url_paramsConstants() {
}



