/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef url_params_CONSTANTS_H
#define url_params_CONSTANTS_H

#include "url_params_types.h"



class url_paramsConstants {
 public:
  url_paramsConstants();

};

extern const url_paramsConstants g_url_params_constants;



#endif
