proto_library (
  name = 'doc_info',
  srcs = 'doc_info.proto',
)

proto_library (
  name = 'raw_doc',
  srcs = 'raw_doc.proto',
)

proto_library (
  name = 'request_params',
  srcs = 'request_params.proto',
)

proto_library (
  name = 'index_search_common_names',
  srcs = 'index_search_common_names.proto',
)
