cc_library (
  name = 'http_server',
  srcs = [
    'http_server.cc',
  ],
  deps = ['//common:base','#event','#event_openssl','#event_pthreads','#evhtp']
)

cc_library (
  name = 'http_client',
  srcs = [
    'http_client.cc',
  ],
  deps = ['//common:base','#event','#event_openssl','#event_pthreads','#evhtp']
)
