cc_binary (
  name = 'test_client',
  srcs = [
    'test_client.cc',
  ],
  deps = [
    '//common:base',
    '//server/http:http_client',
    '#event',
    '#event_openssl',
    '#event_pthreads',
    '#evhtp',
    '#pthread',
  ]
)
